---
title: "Environmental Data"
output: 
  html_document:
    df_print: paged
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    number_sections: FALSE
---

# Download Latest Version of `NNS (>=0.4.5)`
Load Variables:
`GT8134017	GT8134022	GT8134027	GT8134028	GT8153030	GT8153031	GT8172035	GT8172037`

```{r dataload,message=FALSE}
library(devtools); install_github('OVVO-Financial/NNS', ref = "NNS-Beta-Version")
library(NNS)


# Read data
environmental.data <- read.csv("https://raw.githubusercontent.com/OVVO-Financial/Environmental-Forecasting/master/Data/GWL_Final_data.csv",sep = ',',header = TRUE)

environmental.data <- environmental.data[,-c(1,2)]

head(environmental.data)
```

# Create our evaluation formula `NSE`

```{r NSE}
NSE <- function(x,y){
  NSE=1- (sum((x-y)^2)/sum((y-mean(y))^2))
  return(NSE)
}
```


# `NNS` Forecasts
Since we are dealing with highly periodic monthly data, we will use a mod 6 of the `seasonal.factor`s to determine semi-annual cycles.


## 12 and 24 Month Out of Sample Forecast for Each `series`

```{r data1}
NSEs <- list()

for(j in seq_len(ncol(environmental.data))){
    subNSEs <- list()
  
    series <- environmental.data[,j]
  
    for(i in c(12,24)){
        print(paste0(colnames(environmental.data)[j], " ", i, " Month Forecast"))
      
        h <- i 

        # Create a training set
        series.train <- series[1:(length(series) - h)]

        # Create a test set
        series.test <- tail(series, h)

        train_length <- length(series.train) - h

        a <- NNS.seas(series.train)$all.periods$Period
  
        plus <- a+(12-a%%12)
        minus <- a-a%%12

        periods <- unique(c(rbind(minus,plus)))
        periods <- periods[!is.na(periods) & periods>0]


        arma_parameters <- NNS.ARMA.optim(series.train, 
                                          training.set = (length(series.train )-2*h),
                                          seasonal.factor = periods)


        nns_estimates <- NNS.ARMA(series,
                                  training.set = length(series) - h,
                                  h = h, 
                                  method = arma_parameters$method, 
                                  seasonal.factor = arma_parameters$periods, 
                                  weights = arma_parameters$weights,
                                  seasonal.plot = FALSE) + arma_parameters$bias.shift

        # NSE Statistic
        subNSEs[[which(c(12,24)%in%i)]] <- NSE(nns_estimates,tail(series, h))
        
    }
    
    NSEs[[j]] <- unlist(subNSEs)
}
```


# Evaluate Results
```{r NSEs}
NSEs <- do.call(rbind,NSEs)
rownames(NSEs) <- colnames(environmental.data)
colnames(NSEs) <- c("12 month NSE", "24 month NSE")
NSEs
```


